version: '3.7'

services:

  tournament_nginx:
      container_name: tournament_nginx
      build: ./nginx
      ports:
      - '80:80'
      depends_on:
      - tournament_backend
      - tournament_frontend

  tournament_backend:
    container_name: tournament_backend
    # Hostname jest bezpośrednio wykorzystany na froncie w nuxt.config
    hostname: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 3100:3100


  tournament_frontend:
    container_name: tournament_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
     - "3000"    
  

  tournament_db:
    container_name: tournament_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: praca
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
